version: '3'

services:
  app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - redisdb
      - migrate
    env_file:
      - .env
      
  postgresdb:
    restart: always
    image: postgres:alpine
    env_file:
      - .env-non-dev
    ports:
      - 5678:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  redisdb:
    restart: always
    image: redis:alpine
    ports:
      - 6378:6379
    env_file:
      - .env-non-dev
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",
              "postgres://postgres:postgres@postgresdb:5432/postgres?sslmode=disable", "up"]
    depends_on:
      postgresdb:
        condition: service_healthy