// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Card defines model for Card.
type Card struct {
	Cvv    string `json:"cvv"`
	Data   string `json:"data"`
	Id     int    `json:"id"`
	Number string `json:"number"`
	UserId int    `json:"userId"`
}

// Message defines model for Message.
type Message struct {
	Message string `json:"message"`
}

// Product defines model for Product.
type Product struct {
	Article      string `json:"article"`
	Deleted      bool   `json:"deleted"`
	Id           int    `json:"id"`
	Manufacturer string `json:"manufacturer"`
	Name         string `json:"name"`
	Price        int    `json:"price"`
	SellerId     int    `json:"sellerId"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	RefreshToken struct {
		RefreshToken string `json:"refreshToken"`
	} `form:"refreshToken" json:"refreshToken"`
}

// LogoutAllParams defines parameters for LogoutAll.
type LogoutAllParams struct {
	RefreshToken struct {
		RefreshToken string `json:"refreshToken"`
	} `form:"refreshToken" json:"refreshToken"`
}

// RefreshParams defines parameters for Refresh.
type RefreshParams struct {
	RefreshToken struct {
		RefreshToken string `json:"refreshToken"`
	} `form:"refreshToken" json:"refreshToken"`
}

// SignInJSONBody defines parameters for SignIn.
type SignInJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignUpJSONBody defines parameters for SignUp.
type SignUpJSONBody struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Name          string              `json:"name"`
	Password      string              `json:"password"`
	Username      string              `json:"username"`
}

// VerificationParams defines parameters for Verification.
type VerificationParams struct {
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// AddCardJSONRequestBody defines body for AddCard for application/json ContentType.
type AddCardJSONRequestBody = Card

// AddProductJSONRequestBody defines body for AddProduct for application/json ContentType.
type AddProductJSONRequestBody = Product

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody SignInJSONBody

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody SignUpJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/user/cards)
	GetAllCards(ctx echo.Context) error

	// (POST /api/user/cards)
	AddCard(ctx echo.Context) error

	// (DELETE /api/user/cards/{cardId})
	DeleteCard(ctx echo.Context, cardId int) error

	// (GET /api/user/cards/{cardId})
	GetTheCard(ctx echo.Context, cardId int) error

	// (GET /api/user/products)
	GetAllProducts(ctx echo.Context) error

	// (POST /api/user/products)
	AddProduct(ctx echo.Context) error

	// (DELETE /api/user/products/{productId})
	DeleteProduct(ctx echo.Context, productId int) error

	// (GET /api/user/products/{productId})
	GetTheProduct(ctx echo.Context, productId int) error

	// (DELETE /auth//logout)
	Logout(ctx echo.Context, params LogoutParams) error

	// (GET /auth/get-user)
	GetUser(ctx echo.Context) error

	// (DELETE /auth/logout-all)
	LogoutAll(ctx echo.Context, params LogoutAllParams) error

	// (POST /auth/refresh)
	Refresh(ctx echo.Context, params RefreshParams) error

	// (GET /auth/resend-email)
	ResendEmail(ctx echo.Context) error

	// (POST /auth/sign-in)
	SignIn(ctx echo.Context) error

	// (POST /auth/sign-up)
	SignUp(ctx echo.Context) error

	// (GET /auth/verification)
	Verification(ctx echo.Context, params VerificationParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAllCards converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllCards(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllCards(ctx)
	return err
}

// AddCard converts echo context to params.
func (w *ServerInterfaceWrapper) AddCard(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddCard(ctx)
	return err
}

// DeleteCard converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCard(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cardId" -------------
	var cardId int

	err = runtime.BindStyledParameterWithOptions("simple", "cardId", ctx.Param("cardId"), &cardId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cardId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCard(ctx, cardId)
	return err
}

// GetTheCard converts echo context to params.
func (w *ServerInterfaceWrapper) GetTheCard(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cardId" -------------
	var cardId int

	err = runtime.BindStyledParameterWithOptions("simple", "cardId", ctx.Param("cardId"), &cardId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cardId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTheCard(ctx, cardId)
	return err
}

// GetAllProducts converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllProducts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllProducts(ctx)
	return err
}

// AddProduct converts echo context to params.
func (w *ServerInterfaceWrapper) AddProduct(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddProduct(ctx)
	return err
}

// DeleteProduct converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId int

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProduct(ctx, productId)
	return err
}

// GetTheProduct converts echo context to params.
func (w *ServerInterfaceWrapper) GetTheProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId int

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTheProduct(ctx, productId)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	if cookie, err := ctx.Cookie("refreshToken"); err == nil {

		var value struct {
			RefreshToken string `json:"refreshToken"`
		}
		err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refreshToken: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refreshToken is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx, params)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx)
	return err
}

// LogoutAll converts echo context to params.
func (w *ServerInterfaceWrapper) LogoutAll(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutAllParams

	if cookie, err := ctx.Cookie("refreshToken"); err == nil {

		var value struct {
			RefreshToken string `json:"refreshToken"`
		}
		err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refreshToken: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refreshToken is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LogoutAll(ctx, params)
	return err
}

// Refresh converts echo context to params.
func (w *ServerInterfaceWrapper) Refresh(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshParams

	if cookie, err := ctx.Cookie("refreshToken"); err == nil {

		var value struct {
			RefreshToken string `json:"refreshToken"`
		}
		err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refreshToken: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refreshToken is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Refresh(ctx, params)
	return err
}

// ResendEmail converts echo context to params.
func (w *ServerInterfaceWrapper) ResendEmail(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendEmail(ctx)
	return err
}

// SignIn converts echo context to params.
func (w *ServerInterfaceWrapper) SignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignIn(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// Verification converts echo context to params.
func (w *ServerInterfaceWrapper) Verification(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params VerificationParams
	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameter("form", true, false, "token", ctx.QueryParams(), &params.Token)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Verification(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/user/cards", wrapper.GetAllCards)
	router.POST(baseURL+"/api/user/cards", wrapper.AddCard)
	router.DELETE(baseURL+"/api/user/cards/:cardId", wrapper.DeleteCard)
	router.GET(baseURL+"/api/user/cards/:cardId", wrapper.GetTheCard)
	router.GET(baseURL+"/api/user/products", wrapper.GetAllProducts)
	router.POST(baseURL+"/api/user/products", wrapper.AddProduct)
	router.DELETE(baseURL+"/api/user/products/:productId", wrapper.DeleteProduct)
	router.GET(baseURL+"/api/user/products/:productId", wrapper.GetTheProduct)
	router.DELETE(baseURL+"/auth//logout", wrapper.Logout)
	router.GET(baseURL+"/auth/get-user", wrapper.GetUser)
	router.DELETE(baseURL+"/auth/logout-all", wrapper.LogoutAll)
	router.POST(baseURL+"/auth/refresh", wrapper.Refresh)
	router.GET(baseURL+"/auth/resend-email", wrapper.ResendEmail)
	router.POST(baseURL+"/auth/sign-in", wrapper.SignIn)
	router.POST(baseURL+"/auth/sign-up", wrapper.SignUp)
	router.GET(baseURL+"/auth/verification", wrapper.Verification)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXW/bNhf+KwTfF9iNXLlbBmwudpFmQxdgQ4Omyc2QC0Y6ttlSJEtSXj3D/33gh2TZ",
	"ohQ7zoe7+CoGeXxInvOc5zyks8CZKKTgwI3GowXW2RQK4j6eEZXbv1IJCcpQcKPZbGb/mLkEPMLaKMon",
	"eJngnBgSnaB5Y5hyAxNQdpyXxS2o6FdKDeo8+rVlghV8KamCHI/+sr5rR2ELidth7eMmqXyI20+QGev+",
	"T9CaTKB9tmI1sbGnjXUrw5j3CyXyMjNt70QZmjGIRw8YGGge+VYIBoT3RbAgvByTzJSqI46cFPHlpKIZ",
	"xJ1qYGyX6FenCqtVvjd21/C7Omw7enYFysfCLp6DzhSVhgqOR/g9Z5TDwCiSUz4ZSEbMWKgCJ9hQY4Pa",
	"ZXF6cY4TPAOlvaPXr4avhvagQgInkuIR/sENJVgSM3WZSomkqQVQmhGVu6EJmPam3oFBhDHkrZxLReyc",
	"DZ+dPWXsLMwp0FJw7aHw/XDoaklwA9w5JlIymrkvp5+09V7VYqQEq01RA4X78H8FYzzC/0tXxZyGSk5d",
	"GS/rUBOlyNylMhL79eNdllkGWtsvnwxPdtpw34aq8ouseKVBIS4MGouSu13/uGOk7rnwOTegOGFIg5qB",
	"QqCU8IA3ZKIt2F0Yb2ztCB2BwmmeOxi0UHCa52d+3JYOaPNW5PMHO5JP7tJX5oMCbCsGCIY3u4LpSXJ6",
	"TRjNnc8qnYcHp2WySTbpwgd16TFmmbKNtl/duAMcup0j2oadtwjIk0SRAgwou/QCU+vCkl1F2qMqkc3s",
	"GlVC0ghFCwo3e2LunrFtAOnwyKGzTZhpb7regfk4/XbTVdHQ83cQu5PD7iBrJS+9WLxbYtSGcZVxsZp+",
	"wD7Q3N1WWqPSvke5sS9Yqkj2K46QoJjouKinHkN31Il+aOkRTrSV+ljZHgXIHgCLElK6qKO7jRIJxr1i",
	"ZIXIuxvcKrVHSbI/gfSqkv7UeWHyjaeuwVbP33TCZg6+7zhaKM00TZmYiNJswQKWQb7TSIN2jy2bWPrD",
	"+4mDKBPiM4UVjBSMFejpR/EZeC+S1vvH2tfufMdbs440kefnk5Ph6ydRQtymWij6DxwWHgNmGnCcgBlY",
	"oPVKZmcQ4bIrP/6AggUKQpn9MBaqIAaPwkjSfnV1E9eg6Jh2PfV2v9gSrf8WKo9OKtHxrGzD0OFyoxJq",
	"y/odtzpGvfLmAcK6O2qvg0GWg0IDV57lBoSxLZjOXsm2YrtTxo6EdyS8fQgv5MylPnoT/OANkLFZbb8Q",
	"hOmXBMONH94cuLq2luyz92TN+c7X0JcN9RC0JtI18HxQt9Roe//gjNDMtaEsXK9Dr9oEvrX8LcwdL4Y+",
	"6j4ejahrOuEDyrv55dIbxEWVnTznezwz3VtO9UiijZJtSZlYoS7/+5yT4CmQ3NH/Al+CGZx58rdx/0oK",
	"6X5H16KAQVhw4FrKG3RBzPSX9A363Rj5nrN5Ox3Lp3tWe0tyFMD2hCx6zmeE0RxVQjmtwISEQgdLsZsi",
	"19V6KftrHZWyu9av5HPU+qNdnR71hvT4NOP/NaiOX1m6J7z2QQ7wdbxVxj8/xaqu+6VXIZeIMAUknyPf",
	"3Q66dJuCp1McOejNO/TQddND/DbwpQQ1X10GTGg4rXfbGlov5sLoui2iGsFXaSkhpaEhWPpf+x3xoBtC",
	"rf7cv/pZI5/9UjE8wlNj5ChNmcgImwptRj8Nh0O8vFn+GwAA///74Es+JyoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
