// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Card defines model for Card.
type Card struct {
	Cvv    string `json:"cvv"`
	Data   string `json:"data"`
	Id     int    `json:"id"`
	Number string `json:"number"`
	UserId int    `json:"userId"`
}

// Message defines model for Message.
type Message struct {
	Message string `json:"message"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	RefreshToken struct {
		RefreshToken string `json:"refreshToken"`
	} `form:"refreshToken" json:"refreshToken"`
}

// LogoutAllParams defines parameters for LogoutAll.
type LogoutAllParams struct {
	RefreshToken struct {
		RefreshToken string `json:"refreshToken"`
	} `form:"refreshToken" json:"refreshToken"`
}

// RefreshParams defines parameters for Refresh.
type RefreshParams struct {
	RefreshToken struct {
		RefreshToken string `json:"refreshToken"`
	} `form:"refreshToken" json:"refreshToken"`
}

// SignInJSONBody defines parameters for SignIn.
type SignInJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignUpJSONBody defines parameters for SignUp.
type SignUpJSONBody struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Name          string              `json:"name"`
	Password      string              `json:"password"`
	Username      string              `json:"username"`
}

// VerificationParams defines parameters for Verification.
type VerificationParams struct {
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// AddCardJSONRequestBody defines body for AddCard for application/json ContentType.
type AddCardJSONRequestBody = Card

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody SignInJSONBody

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody SignUpJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/user/cards)
	GetAllCards(ctx echo.Context) error

	// (POST /api/user/cards)
	AddCard(ctx echo.Context) error

	// (DELETE /api/user/cards/{cardId})
	DeleteCard(ctx echo.Context, cardId int) error

	// (GET /api/user/cards/{cardId})
	GetTheCard(ctx echo.Context, cardId int) error

	// (DELETE /auth//logout)
	Logout(ctx echo.Context, params LogoutParams) error

	// (DELETE /auth/logout-all)
	LogoutAll(ctx echo.Context, params LogoutAllParams) error

	// (POST /auth/refresh)
	Refresh(ctx echo.Context, params RefreshParams) error

	// (GET /auth/resend-email)
	ResendEmail(ctx echo.Context) error

	// (POST /auth/sign-in)
	SignIn(ctx echo.Context) error

	// (POST /auth/sign-up)
	SignUp(ctx echo.Context) error

	// (GET /auth/verification)
	Verification(ctx echo.Context, params VerificationParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAllCards converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllCards(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllCards(ctx)
	return err
}

// AddCard converts echo context to params.
func (w *ServerInterfaceWrapper) AddCard(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddCard(ctx)
	return err
}

// DeleteCard converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCard(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cardId" -------------
	var cardId int

	err = runtime.BindStyledParameterWithOptions("simple", "cardId", ctx.Param("cardId"), &cardId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cardId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCard(ctx, cardId)
	return err
}

// GetTheCard converts echo context to params.
func (w *ServerInterfaceWrapper) GetTheCard(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cardId" -------------
	var cardId int

	err = runtime.BindStyledParameterWithOptions("simple", "cardId", ctx.Param("cardId"), &cardId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cardId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTheCard(ctx, cardId)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	if cookie, err := ctx.Cookie("refreshToken"); err == nil {

		var value struct {
			RefreshToken string `json:"refreshToken"`
		}
		err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refreshToken: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refreshToken is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx, params)
	return err
}

// LogoutAll converts echo context to params.
func (w *ServerInterfaceWrapper) LogoutAll(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutAllParams

	if cookie, err := ctx.Cookie("refreshToken"); err == nil {

		var value struct {
			RefreshToken string `json:"refreshToken"`
		}
		err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refreshToken: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refreshToken is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LogoutAll(ctx, params)
	return err
}

// Refresh converts echo context to params.
func (w *ServerInterfaceWrapper) Refresh(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshParams

	if cookie, err := ctx.Cookie("refreshToken"); err == nil {

		var value struct {
			RefreshToken string `json:"refreshToken"`
		}
		err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refreshToken: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refreshToken is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Refresh(ctx, params)
	return err
}

// ResendEmail converts echo context to params.
func (w *ServerInterfaceWrapper) ResendEmail(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendEmail(ctx)
	return err
}

// SignIn converts echo context to params.
func (w *ServerInterfaceWrapper) SignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignIn(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// Verification converts echo context to params.
func (w *ServerInterfaceWrapper) Verification(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params VerificationParams
	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameter("form", true, false, "token", ctx.QueryParams(), &params.Token)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Verification(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/user/cards", wrapper.GetAllCards)
	router.POST(baseURL+"/api/user/cards", wrapper.AddCard)
	router.DELETE(baseURL+"/api/user/cards/:cardId", wrapper.DeleteCard)
	router.GET(baseURL+"/api/user/cards/:cardId", wrapper.GetTheCard)
	router.DELETE(baseURL+"/auth//logout", wrapper.Logout)
	router.DELETE(baseURL+"/auth/logout-all", wrapper.LogoutAll)
	router.POST(baseURL+"/auth/refresh", wrapper.Refresh)
	router.GET(baseURL+"/auth/resend-email", wrapper.ResendEmail)
	router.POST(baseURL+"/auth/sign-in", wrapper.SignIn)
	router.POST(baseURL+"/auth/sign-up", wrapper.SignUp)
	router.GET(baseURL+"/auth/verification", wrapper.Verification)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yZUW/bthPAvwrB/x/Yi1y5WwZsKvbgZkNnYEOLpsnL4AdGPFtsKZIlT149Q999ICk5",
	"siWncdM53pInG+TxeLr73R1FrWmuS6MVKHQ0W1OXF1Cy8PecWe5/jdUGLAoIo/ly6X9wZYBm1KEVakHr",
	"hHKGbHBC8M6wUAgLsH5cVeU12MEllQM7HVxWJ9TCx0pY4DT7w+veKGpMSIKFGx2zpNWhr99Djl797+Ac",
	"W0D/2cqbiR2bdvZtBfvavaRQc+11cHC5FQaFVjSjr5UUCkZoGRdqMTKS4VzbkiYUBUrYLzF5M6UJXYJ1",
	"UdHzZ+NnY/8c2oBiRtCMfheGEmoYFuFJUmZE6l2Q5szyMLQA7Bv1CpAwKUmUCiot83Pe/X52IuV5M2fB",
	"Ga1cdNW343GgQSsEFRQzY6TIw+L0vfPaW5oGIGqNEghl+PN/C3Oa0f+lNzimDYtpALHeuJpZy1YhJAO+",
	"3368iyrPwTm/+Gx8dpDBtxnUAjSw46UDS5RGMteVClZ/f6CnvnDjqUKwikniwC7BErBWx4RBtnAe2uDG",
	"WZ1Qo90AChPOAwY9Ciacn8dxnwLg8KXmq6/2SDG4dcywrwrYnSpIIzg7FKajxPSKScGDzjacp4dTnewW",
	"m3QdnVpHxiQg9Gn7OYwH4Mj1iog+dlGiIc8wy0pAsH7rNRVehS92vvyz0setCWQ3umgrSDqu6KEwuydz",
	"X+jbDkinVxz2tgksbg3XK8B3xb83XG0ZevgO4i057Q4SUr7CIk2lXugK75Dnvjp844gDFw4xu/D8FvUM",
	"g5Nr/UHADToW5hZc8U5/AHUrQNstYWvZZ094W9ID3eHhS8fZ+PlRDjTKh1pb8RecFowNMx0cI40jJuUd",
	"iPSn3jtROZHyCcwnMO8DZhOzEPrBs/fbKEDQR7X/HtZMPyYMt21jAa59piX3sT3ZUn7we8DjRr1xWpd0",
	"B4qPoGRC7r10eBuEyBKsmDdGk7iiD76X/KWZezqrR69Hf3S87sRCjYTaX18uokBoeD0n+8mpusfr/Xau",
	"bmI/17ZkSDPaxraXtoY596e2/PMp26rYrBhK1Pq/X3MSWgDjofyv6QXg6DwWf+/3T6w04R7R6RJGzYaj",
	"0FJekDcMi5/SF+RXRPNayVU/HPXx7jVeMk4a2I5YRadqyaTgIQl8q0xbmIi25GRL7KVP2d1cr8ztuU4q",
	"sz/XL81D5HqYuAolH7oJf621BKbCF4FwflkfVCfiRf+elTs5uJFstkr6ZWXXzn++zMTPIxv/VVW4W+k/",
	"yAleT/bS+Mdj7Bq6X3rZxJIwaYHxFYnd7aRTt3vg2Xs4Cuit9pyHrroaht8GPlZgVzcvA9g0nN612gat",
	"R/PCGLotEY7AJ+NLQiqahuDL/9Znm5NuCJvTX53QKBSjX1lJM1ogmixNpc6ZLLTD7IfxeEzrWf13AAAA",
	"//97gZgg6R0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
