port: "8000"

db:
  host: "localhost"
  port: "5678"
  user: "postgres"
  name: "postgres"
  sslmode: "disable"

rdb:
  host: "localhost"
  port: "6378"
  password: "redis"
  db: "0"

smtp:
  email: "IvanMelnikovF@gmail.com"
  host: "smtp.gmail.com"
  port: "587"

tokens:
  refreshTTL: "60d"
  emailTTL: "1h"